// ===== ENDLESS RUNNER - Game State =====
(function() {
    'use strict';
    const SG = window.__SG = window.__SG || {};

    SG.state = {
        score: 0,
        coins: 0,
        speed: SG.START_SPEED || 0.35,
        gameOver: false,
        currentLane: 1,
        isJumping: false,
        isRolling: false,
        jumpVelocity: 0,
        targetLane: 1,
        laneLerp: 1,
        running: true,
        playerHeight: SG.PLAYER_Y || 0.15,
        targetPlayerHeight: SG.PLAYER_Y || 0.15,
        instantSpeedMps: 0,
        _speedSample: null,
        lastObstacleZ: 0,
        minObstacleGap: 30,
        obstacleTimer: 0,
        trackSegments: [],
        obstacles: [],
        coinObjects: [],
        gunPickups: [],
        coinObstacleMap: new Map(),
        buildings: [],
        particles: [],
        cameraShake: 0,
        gameTime: 0,
        scoreTimer: 0,
        instructionTimer: 8,
        hasStartedTouch: false,
        started: false,
        countdownActive: false,
        paused: false,
        startLaneX: 0,
        bestScore: parseInt(localStorage.getItem('subwayBest') || '0'),
        onRoof: false,
        rollEndTime: 0,
        firstPerson: false,
        difficulty: 2,
        homelander: false,
        cyberMode: false,
        laserTimer: 0,
        muted: false,
        musicVolume: parseFloat(localStorage.getItem('subwayMusicVol') || '0.5'),
        sfxVolume: parseFloat(localStorage.getItem('subwaySfxVol') || '0.8'),
        rollReleaseDelay: parseInt(localStorage.getItem('subwayRollReleaseDelay') || '200'),
        thirdPersonView: localStorage.getItem('subwayThirdPersonView') || 'near',
        firstPersonPitchDeg: Math.max(-5, Math.min(5, parseFloat(localStorage.getItem('subwayFirstPersonPitchDeg') || '1'))),
        lastPlayedCoin: 0,
        credits: parseInt(localStorage.getItem('subwayCredits') || '0'),
        totalCoins: parseInt(localStorage.getItem('subwayTotalCoins') || '0'),
        equippedAbility: 0,
        canDoubleJump: false,
        hasDoubleJumped: false,
        canJetpack: false,
        jetpackFuel: 0,
        jetpackCooldown: 0,
        activeGun: null,
        gunTimer: 0,
        gunShotCooldown: 0,
        gunSpawnTimer: 6,
        canRoofWalk: false,
        theme: 0,
        jumpingFromRoof: false,
        rolledLand: false,
        rolledLandTime: 0,
        // Police chase
        policeDistance: 8.0,
        policeChasing: false,
        policeSiren: false,
        policeTotalDistance: 0,
        maxLegitDistance: 0,
        maxEasy: 0,
        maxMedium: 0,
        maxHard: 0,
        maxEasyAbility: 0,
        maxMediumAbility: 0,
        maxHardAbility: 0,
        legitRun: true,
        runCount: 0,
        selectedCharacter: localStorage.getItem('subwaySelectedCharacter') || 'runner',
        ownedCharacters: ['runner']
    };
})();
